### ISSUE TITLE
Thoughts on pattern matching

### ISSUE THREAD

**Issue by kmalakoff** [inikulin/promisify-event#2]
I have a case where I'm listening to an event emitter, but waiting for a specific pattern in the emitted data. Is this a case that you would be interested in supporting with this module?

```
promisifyEvent(emitter, 'eventname', (data) => data.id === 5).then(() => {});
```

**Comment by inikulin** [comment]
It's quite a specific case and I'm not a fan of ad hoc solutions to be honest. Maybe the following utility function will server your needs:
```js
const promisifyEvent = require('promisify-event');

function promisifyEventWithFilter(emitter, event, filter) {
    return new Promise((resolve, reject) => {
         promisifyEvent(emitter, event)
             .then(data => {
                  if (filter(data))
                        resolve(data);
             })
             .catch(reject);
    });
}
```

**Comment by kmalakoff** [comment]
No problem. Just checking to see if it fits. 

I already have some boilerplate for this. Maybe I'll release in a module.

Thanks!
